//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.12 at 05:24:48 PM EDT 
//


package ws.argo.Responder.response.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ws.argo.Responder.response.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ws.argo.Responder.response.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Services.Service.AccessPoints.AccessPoint }
     * 
     */
    public Services.Service.AccessPoints.AccessPoint createServicesServiceAccessPointsAccessPoint() {
        return new Services.Service.AccessPoints.AccessPoint();
    }

    /**
     * Create an instance of {@link Services }
     * 
     */
    public Services createServices() {
        return new Services();
    }

    /**
     * Create an instance of {@link Services.Service }
     * 
     */
    public Services.Service createServicesService() {
        return new Services.Service();
    }

    /**
     * Create an instance of {@link Services.Service.AccessPoints.AccessPoint.Data }
     * 
     */
    public Services.Service.AccessPoints.AccessPoint.Data createServicesServiceAccessPointsAccessPointData() {
        return new Services.Service.AccessPoints.AccessPoint.Data();
    }

    /**
     * Create an instance of {@link Services.Service.AccessPoints }
     * 
     */
    public Services.Service.AccessPoints createServicesServiceAccessPoints() {
        return new Services.Service.AccessPoints();
    }

}
