//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.09 at 11:15:03 AM EDT 
//


package ws.argo.ProbeGenerator.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ws.argo.ProbeGenerator.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ws.argo.ProbeGenerator.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Probe.Scids }
     * 
     */
    public Probe.Scids createProbeScids() {
        return new Probe.Scids();
    }

    /**
     * Create an instance of {@link Probe }
     * 
     */
    public Probe createProbe() {
        return new Probe();
    }

    /**
     * Create an instance of {@link Probe.Ra.RespondTo }
     * 
     */
    public Probe.Ra.RespondTo createProbeRaRespondTo() {
        return new Probe.Ra.RespondTo();
    }

    /**
     * Create an instance of {@link Probe.Ra }
     * 
     */
    public Probe.Ra createProbeRa() {
        return new Probe.Ra();
    }

    /**
     * Create an instance of {@link Probe.Siids }
     * 
     */
    public Probe.Siids createProbeSiids() {
        return new Probe.Siids();
    }

}
